### PR TITLE
 [feature] Add RollingLimit and LifetimeLimit

### PR DESCRIPTION
**Pull request by ashleym1972**
Feature

Reason:
  There was a requirement to have hard limits rather than the windowed limits where the limit could be exceeded in the time period. Additionally, there was a need to have a lifetime (cumulative) and one time limits, which extended from Limit so that the interface would not change.

### CODE REVIEW

**Comment by hudon** [comment]
`Coverage decreased (-0.5%) to 99.535%` wat

**Comment by ashleym1972** [comment]
I left in an unused private method. Oops.

**Comment by hudon** [comment]
I was commenting on how the test coverage was 100.035% :)

**Comment by ashleym1972** [comment]
It is pretty funny.

**Pull request merged**
